services:
  clean-todo:
    container_name: clean-todo-app
    build:
      context: .
      target: dev
    depends_on:
      - postgres
    ports:
      - "9229:9229"
      - "${APP_PORT}:${APP_PORT}"
    tty: true
    command: yarn dev
    volumes:
      - .:/srv/app
      - app_node_modules:/srv/app/node_modules

  postgres:
    container_name: clean-todo-postgres
    image: postgres:10.4
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"

volumes:
  app_node_modules:
  db:
    driver: local
